name: agentic-honeypot
region: blr

services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs

    envs:
      - key: GEMINI_API_KEY
        scope: RUN_TIME
        value: ${GEMINI_API_KEY}
      - key: GUVI_CALLBACK_URL
        scope: RUN_TIME
        value: https://guvi-hackathon.onrender.com/callback
      - key: PYTHONUNBUFFERED
        scope: RUN_TIME
        value: "1"

    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    routes:
      - path: /
